<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Customer Demand – Profit Analytics for Entrepreneurs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./durable_demand.html" rel="next">
<link href="./uncertainty_profit.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-28e1de5e8b558a0209691034755ec9c6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="custom.css">
</head>

<body class="nav-sidebar floating nav-fixed slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Profit Analytics for Entrepreneurs</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./demand.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Customer Demand</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uncertainty_entrepreneurship.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Navigating Uncertainty in Entrepreneurship</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uncertainty_profit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Profit Uncertainty</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./demand.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Customer Demand</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./durable_demand.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimating Demand of Durable Goods Using R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nondurable_demand.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Estimating Demand of Non-durable Goods Using R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cost.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Cost Structure</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cost_dynamics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Cost Dynamics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./profit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Profit</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./competition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Competition</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./entry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Entry and Entry Barriers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./competitive_advantage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Entrepreneurial Profit Dynamics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./non-price_competition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Competing on Things other than Price</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-why-demand" id="toc-sec-why-demand" class="nav-link active" data-scroll-target="#sec-why-demand"><span class="header-section-number">4.1</span> Why Study Demand?</a></li>
  <li><a href="#sec-demand-curves" id="toc-sec-demand-curves" class="nav-link" data-scroll-target="#sec-demand-curves"><span class="header-section-number">4.2</span> Demand Curves</a></li>
  <li><a href="#sec-sensitivity" id="toc-sec-sensitivity" class="nav-link" data-scroll-target="#sec-sensitivity"><span class="header-section-number">4.3</span> Price Sensitivity</a></li>
  <li><a href="#sec-where-demand-curves" id="toc-sec-where-demand-curves" class="nav-link" data-scroll-target="#sec-where-demand-curves"><span class="header-section-number">4.4</span> Where do we get demand curves?</a>
  <ul class="collapse">
  <li><a href="#sec-get-wtp" id="toc-sec-get-wtp" class="nav-link" data-scroll-target="#sec-get-wtp">Collect Willingness to Pay Data</a></li>
  <li><a href="#sec-wtp-q" id="toc-sec-wtp-q" class="nav-link" data-scroll-target="#sec-wtp-q">Use Willingness to Pay Data to Calculate Quantity</a></li>
  <li><a href="#sec-demand-model" id="toc-sec-demand-model" class="nav-link" data-scroll-target="#sec-demand-model">Estimate the Demand Curve</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">4.5</span> Conclusion</a></li>
  <li><a href="#workout-problems" id="toc-workout-problems" class="nav-link" data-scroll-target="#workout-problems"><span class="header-section-number">4.6</span> Workout Problems</a>
  <ul class="collapse">
  <li><a href="#dorsal-packs" id="toc-dorsal-packs" class="nav-link" data-scroll-target="#dorsal-packs">Dorsal Packs</a></li>
  <li><a href="#dorsal-pack-data" id="toc-dorsal-pack-data" class="nav-link" data-scroll-target="#dorsal-pack-data">Dorsal Pack data</a></li>
  <li><a href="#homework-questions" id="toc-homework-questions" class="nav-link" data-scroll-target="#homework-questions">Homework Questions:</a></li>
  </ul></li>
  <li><a href="#sec-elasticity" id="toc-sec-elasticity" class="nav-link" data-scroll-target="#sec-elasticity"><span class="header-section-number">4.7</span> Appendix: Elasticity of Demand</a>
  <ul class="collapse">
  <li><a href="#elasticity-with-linear-demand-curves" id="toc-elasticity-with-linear-demand-curves" class="nav-link" data-scroll-target="#elasticity-with-linear-demand-curves">Elasticity with Linear Demand Curves</a></li>
  <li><a href="#elasticity-with-nonlinear-exponential-demand-curves" id="toc-elasticity-with-nonlinear-exponential-demand-curves" class="nav-link" data-scroll-target="#elasticity-with-nonlinear-exponential-demand-curves">Elasticity with Nonlinear (Exponential) Demand Curves</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-demand-chapter" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Customer Demand</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-why-demand" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="sec-why-demand"><span class="header-section-number">4.1</span> Why Study Demand?</h2>
<p>Successful innovations hinge on being desirable, feasible, and viable. These aspects are interdependent. If an innovation lacks desirability, feasibility alone can’t save it. If it’s not feasible, it can’t meet the desired level of performance. Without desirability and feasibility, viability is unattainable because it can’t sustainably fulfill customer needs. This interplay among desirability, feasibility, and viability defines entrepreneurship as an economic activity, where success is measured by value creation and long-term profitability.</p>
<p>Value isn’t limited to financial profit; it can encompass outcomes like health, dignity, comfort, or spirituality, particularly in ventures with non-profit missions. Even when value isn’t financial, it’s often referred to as profit for measurement purposes, and profitability is a key success metric.</p>
<p>Profit is typically calculated as revenue minus cost, expressed as:</p>
<p><span class="math display">\[\begin{align*}
\mathsf{\pi} &amp;= \mathsf{Revenue - Cost} \\        
     &amp;= \mathsf{R - C} \\        
     &amp;= \mathsf{PQ - cQ -F}
\end{align*}\]</span></p>
<p>Here, <span class="math inline">\(\mathsf{\pi}\)</span> represents profit, <span class="math inline">\(\mathsf{R}\)</span> is revenue, <span class="math inline">\(\mathsf{C}\)</span> is cost, <span class="math inline">\(\mathsf{P}\)</span> is price, <span class="math inline">\(\mathsf{Q}\)</span> is quantity, <span class="math inline">\(\mathsf{c}\)</span> is variable cost, and <span class="math inline">\(\mathsf{F}\)</span> is fixed cost. To achieve viability, a venture must consistently generate positive profit. Notably, the quantity variable <span class="math inline">\(\mathsf{Q}\)</span> represents demand for the solution at the price <span class="math inline">\(\mathsf{P}\)</span>. Demand is a foundational factor in assessing expected profitability.</p>
<p>The surest route to entrepreneurial success is identifying customers with a genuine need and addressing it with a solution. Regardless of the innovation’s technical superiority or other accolades, without customer demand, it won’t succeed commercially. “Better” must be defined in terms of solving customer problems.</p>
<p>From an economic perspective, discovering customer problems equates to finding demand curves. When customers have a problem they want solved, they will “demand” your solution. Conversely, if there’s no demand, even the most remarkable solution will fail commercially. Finding your customers’ demand curve for your solution and analyzing price and revenue potential based on it is crucial.</p>
<p>In established companies, profit components are derived from accounting data. However, in startups, evidence-based decisions require calculating expected profit using demand. In this chapter, we’ll delve into demand curves, their properties, and, most importantly, how to collect customer preference data to identify the demand curve. Armed with this knowledge, we can construct revenue, cost, and profit curves to assess the long-term viability of the venture.</p>
<hr>
</section>
<section id="sec-demand-curves" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-demand-curves"><span class="header-section-number">4.2</span> Demand Curves</h2>
<p>A <strong>demand curve</strong> is a critical concept in understanding customer behavior and revenue generation. It represents the relationship between the price of a product and the quantity customers are willing to buy. Let’s break it down further:</p>
<ul>
<li><strong>Demand Curve Definition:</strong> A demand curve is essentially a graph or mathematical equation that shows how much customers value a product at different prices. In its simplest form, it can be expressed as <span class="math inline">\(\mathsf{Q = a - bP}\)</span>, where <span class="math inline">\(\mathsf{Q}\)</span> is the quantity, and <span class="math inline">\(\mathsf{P}\)</span> is the price. For example, <a href="#fig-q1" class="quarto-xref">Figure&nbsp;<span>4.1</span></a> shows this demand curve graphically. The intercept is 2000 units meaning that 2000 units will be sold when price is $0. For every dollar increase in price, demand falls by 2 units. This demand curve implies that at a price of $750, customers will buy 500 units.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-q1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-q1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="demand_files/figure-html/fig-q1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-q1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: Demand Curve: Q = 2000 - 2P
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>Law of Demand</strong>: The <em>law of demand</em> states that as the price of a product rises, customers tend to buy less of it, and as the price falls, they buy more. This aligns with common shopping behavior: when something becomes more expensive, we often seek alternatives.</p></li>
<li><p><strong>Factors Influencing Demand:</strong> While price is a significant factor, demand curves can be influenced by other variables like income, advertising, and the prices of other goods. A complete demand curve takes these factors into account through a more complex equation, such as <span class="math display">\[\mathsf{Q_x(P_x) = a - bP_x + cP_y + dM + \ldots}\]</span>where <span class="math inline">\(\mathsf{P_x}\)</span> is the price of the product in question, <span class="math inline">\(\mathsf{P_y}\)</span> is the price of another good, and <span class="math inline">\(\mathsf{M}\)</span> is income.</p></li>
<li><p><strong>Changes in Demand vs.&nbsp;Quantity Demanded:</strong> When factors other than the price of the product change, the entire demand curve shifts. As <a href="#fig-change-demand" class="quarto-xref">Figure&nbsp;<span>4.2</span></a> illustrates, this movement from point A to C is known as a <em>change in demand</em>. Conversely, a <em>change in quantity demanded</em> occurs when only the price of the product changes, causing movement along the demand curve from point A to B. For example, an increase in income might lead to a higher demand for a product, shifting the demand. This distinction is important when we work with demand curves with more variables than just price. As you may intuit from the graph, the effect of non-price variables is to change the intercept of the demand curve.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-change-demand" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-change-demand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="demand_files/figure-html/fig-change-demand-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-change-demand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.2: Change in Demand vs.&nbsp;Change in Quantity Demanded
</figcaption>
</figure>
</div>
</div>
</div>
<p>Demand curves are powerful tools for understanding customer behavior and making informed business decisions. They help businesses set appropriate prices, predict customer responses to price changes, and identify the impact of various external factors on product demand.</p>
<hr>
</section>
<section id="sec-sensitivity" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-sensitivity"><span class="header-section-number">4.3</span> Price Sensitivity</h2>
<p>In traditional economics, much emphasis is placed on the concept of price elasticity, which measures how sensitive customers are to changes in prices. Price-sensitive customers are always on the lookout for discounts and quickly reduce their purchases when prices rise slightly. For well-established companies with ample transaction data and small, infrequent price changes, studying price sensitivity through elasticity makes sense—it helps optimize profit.</p>
<p>However, in the entrepreneurial context, where we often lack transaction data and need to directly engage with customers to estimate demand curves across a wide price range, a different approach is more practical. Rather than analyzing price sensitivity indirectly through elasticity, we will focus on how to directly find and estimate demand curves. This approach allows us to analyze everything we need without the need for elasticity calculations.</p>
<p>For those interested in a deeper dive into elasticity, you can explore the appendix in <a href="#sec-elasticity" class="quarto-xref"><span>Section 4.7</span></a>.</p>
<hr>
</section>
<section id="sec-where-demand-curves" class="level2 page-columns page-full" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="sec-where-demand-curves"><span class="header-section-number">4.4</span> Where do we get demand curves?</h2>
<p>In the realm of economics, demand curves play a pivotal role in understanding consumer behavior and market dynamics. These curves provide insights into how consumers respond to changes in prices and other variables, guiding businesses in their decision-making processes. However, acquiring accurate demand curves has often been regarded as a complex task, typically requiring the expertise of economists and statisticians with advanced degrees. Large corporations usually have the resources to employ such experts, enabling them to make informed strategic choices based on well-defined demand curves.</p>
<p>Yet, the landscape is different for most businesses, especially entrepreneurial startups. These ventures often lack the luxury of dedicated economists and statisticians, making them vulnerable to competitive pressures resulting from less-informed decisions. Traditionally, in economics education, students are cautioned about the challenges of statistically determining demand curves. These curves can be elusive due to various factors, including the complex interplay between supply and demand, historical data biases, and endogeneity. As a result, economics textbooks and courses typically provide demand curves as given, and students are not encouraged to delve into the intricate process of estimating them.</p>
<p>The good news, however, is that startups can sidestep the complexities traditionally associated with estimating demand curves. In the modern business landscape, many entrepreneurs are already collecting data as part of their efforts to validate their business models. This process, often referred to as customer development, revolves around confirming whether customers indeed face the problems that a solution aims to address and whether they genuinely desire that solution. If customers do not resonate with the problem-solution fit, entrepreneurs will likely encounter limited demand and customers who are highly price-sensitive.</p>
<p>So, how can startups navigate the demand curve challenge without the need for specialized economists? The answer lies in understanding the concept of “willingness to pay.” Think of a demand curve as a lineup of your customers, standing shoulder to shoulder, ranked in descending order of their willingness to pay – the maximum amount a customer would be willing to pay for a unit of your solution. In essence, willingness to pay is equivalent to a price point.</p>
<p>By harnessing your knowledge of customers’ willingness to pay, you already possess the fundamental elements necessary to estimate a demand curve. This process is more straightforward and less prone to the statistical complexities associated with traditional demand curve estimation. It primarily involves three steps:</p>
<ol type="1">
<li><strong>Collect willingness to pay Data:</strong> Gather data on customers’ willingness to pay, effectively using it as a proxy for price.</li>
<li><strong>Use willingness to pay Data for Quantity Calculation:</strong> Utilize the willingness to pay data to calculate the corresponding quantities customers are willing to purchase at various price points.</li>
<li><strong>Estimate the Demand Curve:</strong> Apply regression analysis to the price-quantity data, allowing you to construct an accurate demand curve. In the subsequent sections, we will delve into these steps in greater detail, exploring how to obtain the data and transform it into valuable insights for your startup.</li>
</ol>
<section id="sec-get-wtp" class="level3">
<h3 class="anchored" data-anchor-id="sec-get-wtp">Collect Willingness to Pay Data</h3>
<p>Gaining insights into your customers’ willingness to pay is crucial for understanding demand. To collect this data effectively, follow these steps:</p>
<ol type="1">
<li><p><strong>Describe the Solution:</strong> Begin by providing a comprehensive description of your product or service. Ensure respondents understand your solution as if they were making a purchase. Even in the early stages, offer the best and most recent description possible.</p></li>
<li><p><strong>Ask Customers Their Willingness to Pay:</strong> After describing the solution, convey your commitment to addressing your customers’ problems and improving their lives through your solution. Ask them, “What is the most you would be willing to pay for this solution?” Record their responses, preferably in a spreadsheet.<br>
<br>
Keep in mind that respondents may provide flawed estimates as they may not fully consider all factors involved in an actual transaction. Some may overestimate their willingness to pay during a survey, while others may underestimate it. However, willingness to pay data still provides remarkably accurate insights into demand.<br>
<br>
Avoid softening the question by naming a specific price and asking if they would buy at that price, as this limits the richness of the data you can gather. Remember that asking this question is not impolite when you genuinely offer a solution to a real problem. Non-customers’ responses, which tend to be biased, should be avoided as they may lead to incorrect validation or rejection of your idea.</p></li>
</ol>
<ul>
<li><p><strong>Minimize Sampling Bias:</strong> Gather data primarily from your target customers to avoid non-relevant responses that can distort your findings.</p></li>
<li><p><strong>Sample Enough Customers:</strong> While a larger sample size is generally better, focus more on refining your understanding of the questions and sampling the right customers. Small, inexpensive samples (30–50 responses) are suitable for refining your understanding, but larger, more expensive samples are needed when seeking a representative demand curve.</p></li>
</ul>
<ol start="3" type="1">
<li><strong>Collect Customer Characteristic Data:</strong> Over time, your understanding of your customers will evolve. To aid this process, request basic demographic information, such as age, gender, income level, education, job category, and geography. As you refine your hypotheses, add new questions about customer characteristics to narrow your focus to real customers while minimizing bias in your sampling.</li>
</ol>
<p>By gathering willingness to pay data and continually refining your understanding of your customers, you can better identify your target audience and tailor your efforts to serve them effectively.</p>
</section>
<section id="sec-wtp-q" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="sec-wtp-q">Use Willingness to Pay Data to Calculate Quantity</h3>
<p>As established in <a href="#sec-demand-curves" class="quarto-xref"><span>Section 4.2</span></a>, a demand curve essentially illustrates the relationship between price and the quantity that consumers are willing to consume at that price. Willingness to pay data provides a proxy for price but where do we get the quantity variable? Let’s look first at the class of products known as durable goods which, as the name implies, are items that endure over time and are not fully consumed in their initial use, such as cars, personal computers, or houses.</p>
<p>Typically, consumers do not purchase more than one unit of a durable good within a short time frame because these products provide sustained value. Consequently, when dealing with durable goods, the quantity of consumers willing to buy is often synonymous with the quantity of the product sold at a given price. In simpler terms, you can count the number of consumers willing to buy at a specific price, and that number represents the quantity demanded at that price.</p>
<p>Let’s consider a sample of willingness to pay data to illustrate this concept. Willingness to pay responses for 27 respondents are given in <a href="#tbl-wtp-data" class="quarto-xref">Table&nbsp;<span>4.1</span></a>.</p>
<div class="cell page-columns page-full" data-tbl-cap-location="margin">
<div id="tbl-wtp-data" class="cell quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-tbl-cap-location="margin">
<figure class="quarto-float quarto-float-tbl figure page-columns page-full">
<div aria-describedby="tbl-wtp-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="xzahbnhrbv" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#xzahbnhrbv table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#xzahbnhrbv thead, #xzahbnhrbv tbody, #xzahbnhrbv tfoot, #xzahbnhrbv tr, #xzahbnhrbv td, #xzahbnhrbv th {
  border-style: none;
}

#xzahbnhrbv p {
  margin: 0;
  padding: 0;
}

#xzahbnhrbv .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xzahbnhrbv .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#xzahbnhrbv .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xzahbnhrbv .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xzahbnhrbv .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xzahbnhrbv .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xzahbnhrbv .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xzahbnhrbv .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xzahbnhrbv .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xzahbnhrbv .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xzahbnhrbv .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xzahbnhrbv .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xzahbnhrbv .gt_spanner_row {
  border-bottom-style: hidden;
}

#xzahbnhrbv .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#xzahbnhrbv .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xzahbnhrbv .gt_from_md > :first-child {
  margin-top: 0;
}

#xzahbnhrbv .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xzahbnhrbv .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xzahbnhrbv .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#xzahbnhrbv .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#xzahbnhrbv .gt_row_group_first td {
  border-top-width: 2px;
}

#xzahbnhrbv .gt_row_group_first th {
  border-top-width: 2px;
}

#xzahbnhrbv .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xzahbnhrbv .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#xzahbnhrbv .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#xzahbnhrbv .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xzahbnhrbv .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xzahbnhrbv .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xzahbnhrbv .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#xzahbnhrbv .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xzahbnhrbv .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xzahbnhrbv .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xzahbnhrbv .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xzahbnhrbv .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xzahbnhrbv .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xzahbnhrbv .gt_left {
  text-align: left;
}

#xzahbnhrbv .gt_center {
  text-align: center;
}

#xzahbnhrbv .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xzahbnhrbv .gt_font_normal {
  font-weight: normal;
}

#xzahbnhrbv .gt_font_bold {
  font-weight: bold;
}

#xzahbnhrbv .gt_font_italic {
  font-style: italic;
}

#xzahbnhrbv .gt_super {
  font-size: 65%;
}

#xzahbnhrbv .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#xzahbnhrbv .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#xzahbnhrbv .gt_indent_1 {
  text-indent: 5px;
}

#xzahbnhrbv .gt_indent_2 {
  text-indent: 10px;
}

#xzahbnhrbv .gt_indent_3 {
  text-indent: 15px;
}

#xzahbnhrbv .gt_indent_4 {
  text-indent: 20px;
}

#xzahbnhrbv .gt_indent_5 {
  text-indent: 25px;
}

#xzahbnhrbv .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#xzahbnhrbv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="respondent" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">respondent</th>
<th id="wtp" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">wtp</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">1</td>
<td class="gt_row gt_right" headers="wtp">15.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">2</td>
<td class="gt_row gt_right" headers="wtp">5.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">3</td>
<td class="gt_row gt_right" headers="wtp">20.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">4</td>
<td class="gt_row gt_right" headers="wtp">15.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">5</td>
<td class="gt_row gt_right" headers="wtp">12.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">6</td>
<td class="gt_row gt_right" headers="wtp">0.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">7</td>
<td class="gt_row gt_right" headers="wtp">10.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">8</td>
<td class="gt_row gt_right" headers="wtp">35.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">9</td>
<td class="gt_row gt_right" headers="wtp">17.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">10</td>
<td class="gt_row gt_right" headers="wtp">0.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">11</td>
<td class="gt_row gt_right" headers="wtp">20.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">12</td>
<td class="gt_row gt_right" headers="wtp">0.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">13</td>
<td class="gt_row gt_right" headers="wtp">22.99</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">14</td>
<td class="gt_row gt_right" headers="wtp">25.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">15</td>
<td class="gt_row gt_right" headers="wtp">15.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">16</td>
<td class="gt_row gt_right" headers="wtp">0.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">17</td>
<td class="gt_row gt_right" headers="wtp">10.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">18</td>
<td class="gt_row gt_right" headers="wtp">15.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">19</td>
<td class="gt_row gt_right" headers="wtp">0.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">20</td>
<td class="gt_row gt_right" headers="wtp">0.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">21</td>
<td class="gt_row gt_right" headers="wtp">20.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">22</td>
<td class="gt_row gt_right" headers="wtp">3.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">23</td>
<td class="gt_row gt_right" headers="wtp">15.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">24</td>
<td class="gt_row gt_right" headers="wtp">30.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">25</td>
<td class="gt_row gt_right" headers="wtp">15.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="respondent">26</td>
<td class="gt_row gt_right" headers="wtp">20.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="respondent">27</td>
<td class="gt_row gt_right" headers="wtp">23.00</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-tbl margin-caption" id="tbl-wtp-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.1: Willingness to pay for each of 27 respondents.
</figcaption>
</figure>
</div>
</div>
<p>In this example, you can observe that two respondents were willing to pay $30 or more for the product, and six out of 27 respondents indicated they would not pay anything, which raises concerns about non-target customers.</p>
<p>The first step in converting this willingness to pay data into quantity data is to count how frequently the unique values of willingness to pay were named. In our example, there are 13 unique values of willingness to pay named by the 27 respondents. The unique values and the count of how frequently they were named are given in <a href="#tbl-wtp-count" class="quarto-xref">Table&nbsp;<span>4.2</span></a>.</p>
<div class="cell page-columns page-full" data-tbl-cap-location="margin">
<div id="tbl-wtp-count" class="cell quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-tbl-cap-location="margin">
<figure class="quarto-float quarto-float-tbl figure page-columns page-full">
<div aria-describedby="tbl-wtp-count-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="tfguppgkwp" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#tfguppgkwp table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#tfguppgkwp thead, #tfguppgkwp tbody, #tfguppgkwp tfoot, #tfguppgkwp tr, #tfguppgkwp td, #tfguppgkwp th {
  border-style: none;
}

#tfguppgkwp p {
  margin: 0;
  padding: 0;
}

#tfguppgkwp .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#tfguppgkwp .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#tfguppgkwp .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#tfguppgkwp .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#tfguppgkwp .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#tfguppgkwp .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tfguppgkwp .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#tfguppgkwp .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#tfguppgkwp .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#tfguppgkwp .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#tfguppgkwp .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#tfguppgkwp .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#tfguppgkwp .gt_spanner_row {
  border-bottom-style: hidden;
}

#tfguppgkwp .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#tfguppgkwp .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#tfguppgkwp .gt_from_md > :first-child {
  margin-top: 0;
}

#tfguppgkwp .gt_from_md > :last-child {
  margin-bottom: 0;
}

#tfguppgkwp .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#tfguppgkwp .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#tfguppgkwp .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#tfguppgkwp .gt_row_group_first td {
  border-top-width: 2px;
}

#tfguppgkwp .gt_row_group_first th {
  border-top-width: 2px;
}

#tfguppgkwp .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#tfguppgkwp .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#tfguppgkwp .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#tfguppgkwp .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tfguppgkwp .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#tfguppgkwp .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#tfguppgkwp .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#tfguppgkwp .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#tfguppgkwp .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tfguppgkwp .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#tfguppgkwp .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#tfguppgkwp .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#tfguppgkwp .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#tfguppgkwp .gt_left {
  text-align: left;
}

#tfguppgkwp .gt_center {
  text-align: center;
}

#tfguppgkwp .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#tfguppgkwp .gt_font_normal {
  font-weight: normal;
}

#tfguppgkwp .gt_font_bold {
  font-weight: bold;
}

#tfguppgkwp .gt_font_italic {
  font-style: italic;
}

#tfguppgkwp .gt_super {
  font-size: 65%;
}

#tfguppgkwp .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#tfguppgkwp .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#tfguppgkwp .gt_indent_1 {
  text-indent: 5px;
}

#tfguppgkwp .gt_indent_2 {
  text-indent: 10px;
}

#tfguppgkwp .gt_indent_3 {
  text-indent: 15px;
}

#tfguppgkwp .gt_indent_4 {
  text-indent: 20px;
}

#tfguppgkwp .gt_indent_5 {
  text-indent: 25px;
}

#tfguppgkwp .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#tfguppgkwp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="wtp" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">wtp</th>
<th id="count" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">count</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">0.00</td>
<td class="gt_row gt_right" headers="count">6</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="wtp">3.00</td>
<td class="gt_row gt_right" headers="count">1</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">5.00</td>
<td class="gt_row gt_right" headers="count">1</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="wtp">10.00</td>
<td class="gt_row gt_right" headers="count">2</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">12.00</td>
<td class="gt_row gt_right" headers="count">1</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="wtp">15.00</td>
<td class="gt_row gt_right" headers="count">6</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">17.00</td>
<td class="gt_row gt_right" headers="count">1</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="wtp">20.00</td>
<td class="gt_row gt_right" headers="count">4</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">22.99</td>
<td class="gt_row gt_right" headers="count">1</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="wtp">23.00</td>
<td class="gt_row gt_right" headers="count">1</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">25.00</td>
<td class="gt_row gt_right" headers="count">1</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="wtp">30.00</td>
<td class="gt_row gt_right" headers="count">1</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">35.00</td>
<td class="gt_row gt_right" headers="count">1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-tbl margin-caption" id="tbl-wtp-count-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.2: Unique values of willingness to pay for the product named by the respondents and a count of how frequently each willingness to pay value was named.
</figcaption>
</figure>
</div>
</div>
<p>Count is similar to quantity but will not really serve as a measure of quantity because it neglects the impact of the law of demand. If you were to accept count as your quantity variable, your demand curve would imply that six units are consumed at a price of $15.00 but only one unit is consumed at a price of $12. The law of demand requires that quantity increase as price falls so <code>count</code> violates that law. We can restate the law of demand to say that anyone who would buy at a higher price would also buy at a lower price. This means that the respondent who is willing to pay $35 is also willing to pay $30 and should be included in the quantity data for $30; the respondent who is willing to pay \$30 and the respondent who is willing to pay \$35 are both also willing to pay \$25 and should be included in the quantity data for \$25; and so on.</p>
<p>To calculate the quantity, start with the highest willingness to pay respondent and use that count as quantity. For the next highest willingness to pay value, add the count of that price to the quantity of the higher willingness to pay respondent. Continue accumulating these values through the lowest willingness to pay value.This cumulative sum approach ensures that the quantity at a lower price includes respondents who are also willing to buy at higher prices, adhering to the law of demand. The resulting price-quantity data can be used to estimate the demand curve for the durable good. The quantity and count variables are shown together with the willingness to pay variable in Table <a href="#tbl-wtp-q" class="quarto-xref">Table&nbsp;<span>4.3</span></a>.</p>
<div class="cell page-columns page-full" data-tbl-cap-location="margin">
<div id="tbl-wtp-q" class="cell quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-tbl-cap-location="margin">
<figure class="quarto-float quarto-float-tbl figure page-columns page-full">
<div aria-describedby="tbl-wtp-q-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="xqdraajxal" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#xqdraajxal table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#xqdraajxal thead, #xqdraajxal tbody, #xqdraajxal tfoot, #xqdraajxal tr, #xqdraajxal td, #xqdraajxal th {
  border-style: none;
}

#xqdraajxal p {
  margin: 0;
  padding: 0;
}

#xqdraajxal .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xqdraajxal .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#xqdraajxal .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xqdraajxal .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xqdraajxal .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xqdraajxal .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xqdraajxal .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xqdraajxal .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xqdraajxal .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xqdraajxal .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xqdraajxal .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xqdraajxal .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xqdraajxal .gt_spanner_row {
  border-bottom-style: hidden;
}

#xqdraajxal .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#xqdraajxal .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xqdraajxal .gt_from_md > :first-child {
  margin-top: 0;
}

#xqdraajxal .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xqdraajxal .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xqdraajxal .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#xqdraajxal .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#xqdraajxal .gt_row_group_first td {
  border-top-width: 2px;
}

#xqdraajxal .gt_row_group_first th {
  border-top-width: 2px;
}

#xqdraajxal .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqdraajxal .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#xqdraajxal .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#xqdraajxal .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xqdraajxal .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqdraajxal .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xqdraajxal .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#xqdraajxal .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xqdraajxal .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xqdraajxal .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xqdraajxal .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqdraajxal .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xqdraajxal .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqdraajxal .gt_left {
  text-align: left;
}

#xqdraajxal .gt_center {
  text-align: center;
}

#xqdraajxal .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xqdraajxal .gt_font_normal {
  font-weight: normal;
}

#xqdraajxal .gt_font_bold {
  font-weight: bold;
}

#xqdraajxal .gt_font_italic {
  font-style: italic;
}

#xqdraajxal .gt_super {
  font-size: 65%;
}

#xqdraajxal .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#xqdraajxal .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#xqdraajxal .gt_indent_1 {
  text-indent: 5px;
}

#xqdraajxal .gt_indent_2 {
  text-indent: 10px;
}

#xqdraajxal .gt_indent_3 {
  text-indent: 15px;
}

#xqdraajxal .gt_indent_4 {
  text-indent: 20px;
}

#xqdraajxal .gt_indent_5 {
  text-indent: 25px;
}

#xqdraajxal .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#xqdraajxal div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="wtp" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">wtp</th>
<th id="count" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">count</th>
<th id="quantity" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">quantity</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">35.00</td>
<td class="gt_row gt_right" headers="count">1</td>
<td class="gt_row gt_right" headers="quantity">1</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="wtp">30.00</td>
<td class="gt_row gt_right" headers="count">1</td>
<td class="gt_row gt_right" headers="quantity">2</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">25.00</td>
<td class="gt_row gt_right" headers="count">1</td>
<td class="gt_row gt_right" headers="quantity">3</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="wtp">23.00</td>
<td class="gt_row gt_right" headers="count">1</td>
<td class="gt_row gt_right" headers="quantity">4</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">22.99</td>
<td class="gt_row gt_right" headers="count">1</td>
<td class="gt_row gt_right" headers="quantity">5</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="wtp">20.00</td>
<td class="gt_row gt_right" headers="count">4</td>
<td class="gt_row gt_right" headers="quantity">9</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">17.00</td>
<td class="gt_row gt_right" headers="count">1</td>
<td class="gt_row gt_right" headers="quantity">10</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="wtp">15.00</td>
<td class="gt_row gt_right" headers="count">6</td>
<td class="gt_row gt_right" headers="quantity">16</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">12.00</td>
<td class="gt_row gt_right" headers="count">1</td>
<td class="gt_row gt_right" headers="quantity">17</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="wtp">10.00</td>
<td class="gt_row gt_right" headers="count">2</td>
<td class="gt_row gt_right" headers="quantity">19</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">5.00</td>
<td class="gt_row gt_right" headers="count">1</td>
<td class="gt_row gt_right" headers="quantity">20</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="wtp">3.00</td>
<td class="gt_row gt_right" headers="count">1</td>
<td class="gt_row gt_right" headers="quantity">21</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="wtp">0.00</td>
<td class="gt_row gt_right" headers="count">6</td>
<td class="gt_row gt_right" headers="quantity">27</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-tbl margin-caption" id="tbl-wtp-q-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.3: Willingness to pay, count, and quantity data for demand estimation.
</figcaption>
</figure>
</div>
</div>
<p>To summarize, here’s a step-by-step approach to obtain quantity data from willingness to pay data:</p>
<ol type="1">
<li>Sort the willingness to pay data in ascending order.</li>
<li>Count the number of respondents willing to pay at each unique price point.</li>
<li>Calculate the quantity demanded at each price by cumulatively summing the count data.</li>
</ol>
</section>
<section id="sec-demand-model" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="sec-demand-model">Estimate the Demand Curve</h3>
<p>In the process of constructing a function of the expected profit to be earned by an innovation, we need the demand curve as the first building block. The demand curve is an equation that shows the quantity demanded at every price. We have data from representative consumers showing prices and the quantities that will be demanded at those prices. We need to convert those data into an equation, and to do that, we will use linear regression.</p>
<p>There are literally dozens of choices of software that will estimate the demand curve equation from price-quantity data. This book gives a detailed explanation of the process using three common analytics platforms: spreadsheet, R, and Python. Depending on your skills and preferences, choose your preferred platform and learn the details about using that platform for estimating the demand curve through regression. In this chapter, we will remain neutral about the estimation platform and invite it to you to explore the particulars of your preferred platform in the supplementary documents dedicated to your platform. For example, throughout this book on entrepreneurship analytics, we will study the expected profitability of Muscle Cola, a hypothetical protein infused soft drink that provides protein replenishment and refreshment after a workout.</p>
<p>At this stage, we will just report the demand estimation of the data collected and reported above and consider how to interpret the regression results as the demand equation. While regression results are reported differently by different analytics platforms, they all have the same components: the regression estimates of the variable coefficients, standard errors of the estimated coefficients, t-statistics for the estimated coefficients, and a variety of measures of the goodness of the statistical fit.</p>
<p>Let’s dig into the regression results for the quantity demanded of a durable good as a function of price. The data for this regression model were presented in <a href="#tbl-wtp-q" class="quarto-xref">Table&nbsp;<span>4.3</span></a>. There, willingness to pay (<code>wtp)</code> serves as a proxy for the independent, predictor variable of <code>price</code>. Changes in the dependent variable <code>quantity</code> are caused by changes in price. We use linear regression as a statistical method used to model the relationship between two variables by fitting a linear equation to observed data. In a linear relationship, one variable changes at a constant rate relative to another <span class="math inline">\(\mathsf{y = b_0 + b_1 x}\)</span>. This relationship can be visualized through a straight line when the data is plotted on a graph, hence the term “linear.”</p>
<p>Let’s start our analysis of the demand curve by visualizing of the relationship between our dependent variable <code>quantity</code> and our independent variable <code>wtp</code> in a scatterplot. This scatterplot is shown in <a href="#fig-wtp-q" class="quarto-xref">Figure&nbsp;<span>4.3</span></a>.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-wtp-q" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-cap-location="margin">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-wtp-q-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="demand_files/figure-html/fig-wtp-q-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-wtp-q-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.3: Scatterplot of the relationship between price and quantity.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Visually, the relationship looks linear and the impact of <code>wtp</code> on <code>quantity</code> seems clear and strongly negative as we would expect.</p>
<section id="use-linear-regression-analysis" class="level4">
<h4 class="anchored" data-anchor-id="use-linear-regression-analysis">Use Linear Regression Analysis</h4>
<p>Using regression, we can get the specific linear equation of the relationship between price and quantity sold. <!--# The `lm()` function in R is a fundamental tool for linear modeling, particularly useful in the realm of regression analysis as part of data modeling. It stands for "linear model" and --> Linear regression is employed to fit linear models to datasets, enabling the analysis of the relationship between two or more variables by choosing coefficients that minimize the difference between the observed and predicted values of the dependent variable.</p>
<p><strong>Model Interpretation:</strong> The summary of the linear model gives details about the coefficients of the equation, error estimates, and other statistical measures. Interpreting the summary of a linear regression model involves evaluating various statistical metrics to understand the model’s performance and validity. Here are the key components:</p>
<ul>
<li><strong>Estimate:</strong> These are the estimated coefficients of the model. In the context of a simple linear regression model <span class="math inline">\(\mathsf{y = b_0 + b_1\ x_1}\)</span>, <span class="math inline">\(\mathsf{b_0}\)</span> is the y-intercept (the value of <span class="math inline">\(\mathsf{y}\)</span> when <span class="math inline">\(\mathsf{x = 0}\)</span>), and <span class="math inline">\(\mathsf{b_1}\)</span> is the slope, indicating the change in <span class="math inline">\(\mathsf{y}\)</span> for a one-unit change in <span class="math inline">\(\mathsf{x}\)</span>.</li>
<li><strong>Std. Error:</strong> This measures the variability in the estimate for the coefficient. Lower values indicate more reliable estimates.</li>
<li><strong>t value:</strong> It’s the coefficient divided by its standard error. It tests the hypothesis that the coefficient is equal to zero (no effect). A t-value of 2 would indicate that the coefficient is two standard errors away from 0.</li>
<li><strong>Pr(&gt;|t|) or p-value:</strong> A low p-value (typically ≤ 0.05) indicates that you can reject the null hypothesis that the coefficient is zero.
<ul>
<li>In other words, a low p-value gives you confidence that the relationship between <span class="math inline">\(\mathsf{y}\)</span> and <span class="math inline">\(\mathsf{x}\)</span> is not just random correlation.<br>
</li>
<li>In fact, the p-value can be interpreted as the level of confidence you can have: p = 0.05 means that there is only a five percent chance that the relationship is actually random rather than a meaningful relationship where <span class="math inline">\(\mathsf{x}\)</span> is influencing <span class="math inline">\(\mathsf{y}\)</span>.<br>
</li>
<li>We typically say that we have 95 percent confidence about the estimate in this case.</li>
<li>Technically, this means that if we repeated the data collection and estimation 100 times, we would expect that in five of the 100 cases our estimate would actually be zero rather than the estimated coefficient.</li>
</ul></li>
</ul>
<p>In addition to examining individual coefficients, understanding the overall fit of a linear regression model is crucial. The summary of a linear regression model provides essential statistics to assess the model’s performance and validity. Here are key components related to the overall model fit:</p>
<ul>
<li><strong>R-squared:</strong> R-squared is a measure of how well the independent variables explain the variability in the dependent variable. It ranges from 0 to 1 and represents the proportion of variance in the dependent variable that is explained by the independent variables.
<ul>
<li>An R-squared value of 0.0 indicates that the model explains none of the variance, while an R-squared of 1.0 means that the model explains all of the variance.</li>
<li>For example, if R-squared is 0.80, it suggests that 80% of the variance in the dependent variable can be attributed to the independent variables included in the model.</li>
<li>R-squared is often interpreted as the goodness of fit, where higher values indicate a better fit.</li>
</ul></li>
<li><strong>F-statistic:</strong> The F-statistic assesses the overall significance of the regression model. It tests the null hypothesis that all coefficients in the model are equal to zero, meaning that the independent variables have no effect on the dependent variable.
<ul>
<li>A high F-statistic indicates that the model as a whole is statistically significant, meaning that at least one of the independent variables is contributing significantly to explaining the variance in the dependent variable.</li>
<li>The F-statistic is associated with a p-value (typically ≤ 0.05), and a low p-value suggests that the model is statistically significant.</li>
<li>If the F-statistic is significant, it implies that the regression equation, as a whole, provides meaningful information about the relationship between the independent and dependent variables.</li>
</ul></li>
</ul>
<p>In summary, R-squared provides insight into how well the independent variables collectively explain the variation in the dependent variable. A higher R-squared indicates a better fit. The F-statistic and its associated p-value evaluate whether the model, as a whole, is statistically significant. If the p-value is low, it suggests that the model is meaningful and provides valuable insights into the relationship between the variables.</p>
</section>
<section id="estimating-demand-for-the-willingness-to-pay-data" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="estimating-demand-for-the-willingness-to-pay-data">Estimating Demand for the Willingness to Pay Data</h4>
<p>Consider the output from the regression of our transformed data on <code>quantity</code> and <code>price</code>, using the <code>lm</code> function from R.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = quantity ~ wtp, data = wtp_q_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.9395 -1.6873 -0.3017  1.8244  3.5091 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 25.04943    1.18871   21.07 3.05e-10 ***
wtp         -0.78739    0.06062  -12.99 5.13e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.222 on 11 degrees of freedom
Multiple R-squared:  0.9388,    Adjusted R-squared:  0.9332 
F-statistic: 168.7 on 1 and 11 DF,  p-value: 5.13e-08</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("gtsummary")</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#library(gtsummary)</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#tbl_regression(demand_model, intercept=T)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Model Interpretation:</strong></p>
<ul>
<li><p>In terms of overall model fit, we see that the F-statistic of 168.7384997 is significantly different from zero meaning that the model fits well. The R-squared value is 0.9388 meaning that we are explaining 93.88 percent of the variance of quantity. Given the variance we saw in the plot, it is not surprising that the R-squared is not terribly high.</p></li>
<li><p>In terms of the impact of price on quantity, we see that the estimated coefficient for price is negative as the law of demand dictates. We also see that the estimated coefficient of price is significantly different from zero with a t-value of -12.9899384 and a p-value of 5.1295431^{-8} which is very close to zero.</p></li>
<li><p>The estimated demand curve for the durable good is <span class="math display">\[ \mathsf{Q = 25.0494315 -0.7873875 P} \]</span> where <code>wtp</code> serves as a proxy for <code>price</code>. In simple terms, this demand curve suggests that for every $1.00 increase in the price of the durable good, the quantity demanded in the sample of respondents decreases by 0.7874 units of the product.</p></li>
<li><p>Visually and empirically we can see that the relationship is linear, meaning that it has the form <span class="math inline">\(\mathsf{y = mx + b}\)</span> or, more commonly analytics, <span class="math inline">\(\mathsf{y = b_0 + b_1 \ x}\)</span>. Not all data exhibit this clear linear relationship and we will address how to estimate nonlinear relationships later.</p></li>
</ul>
<p>For a visual representation of the demand data and the estimated demand curve, refer to <a href="durable_demand.html#fig-wtp-q-fn" class="quarto-xref">Figure&nbsp;<span>5.2</span></a>. Based on the estimated coefficients and the robust goodness-of-fit statistics, we have confidence that the demand curve accurately represents the behavior of consumers. By sampling actual customers and asking relevant questions about their willingness to pay for this durable good, we have obtained a reliable estimate of the demand curve, which serves as a crucial element in constructing the profit function.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-wtp-q-fn" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-cap-location="margin">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-wtp-q-fn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="demand_files/figure-html/fig-wtp-q-fn-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-wtp-q-fn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.4: Demand data and estimated demand curve.
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="conclusion" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">4.5</span> Conclusion</h2>
<p>In the world of evidence-based entrepreneurship, we don’t rely on guesswork; we use judgment rooted in evidence to guide our decisions and actions. This shift from guesswork to informed judgment involves crafting hypotheses and testing them through experiments. Ultimately, all these tests revolve around a fundamental question: Is our innovation viable?</p>
<p>The litmus test for viability lies in customer validation. If customers confirm that they have a problem and believe our solution can solve it, they’re more likely to buy. This is the essence of demand. Moreover, not all customers are created equal. Some may prefer our solution more than others, leading to variations in demand. Additionally, the channel through which we sell our product or service can significantly impact demand.</p>
<p>While traditional business model validation tests may not explicitly estimate the demand curve, they help us understand if the demand curve exists, and if so, its strength.</p>
<p>One of the most robust ways to gauge the viability of an innovation is by calculating its expected profitability using evidence gathered from customers. In the early stages of testing, we focus on validation tests to ascertain if any demand for the solution exists. As we progress and the solution evolves, we transition to calculating expected profits, leveraging the evidence at hand. Customer demand serves as the cornerstone of profitability calculations. Once we accurately estimate the demand curve, it becomes our compass for navigating the intricacies of revenue, cost, and ultimately, profitability.</p>
<p>In seeking evidence for the key decisions in a startup, demand isn’t just a concept; it’s the catalyst that enables us to predict the decisions that lead to success.</p>
</section>
<section id="workout-problems" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="workout-problems"><span class="header-section-number">4.6</span> Workout Problems</h2>
<section id="dorsal-packs" class="level3">
<h3 class="anchored" data-anchor-id="dorsal-packs">Dorsal Packs</h3>
<p>After receiving warnings about the risks of pickpockets when traveling to international tourist destinations, a group of entrepreneurs compared notes about their international travel experiences. They found that they had all experienced some anxiety about their own safety and the security of their belongings in popular tourist destinations. More importantly, they had all taken some steps to try to protect against pickpockets and thieves.</p>
<p>To confirm their personal experiences, they talked with many others who had also traveled to tourist destinations. They confirmed that thieves are active in those places and that even travelers who had not lost possessions suffered anxiety about the risk and took steps to protect their belongings. One common problem that came up in those discussions is that the zippers that make our bags simultaneously accessible and secure also make our bags accessible to thieves. An experienced pickpocket can unzip a backpack, take its contents, and flee before the wearer notices. Possessions are also lost when a thief slashes the fabric at the bottom of a backpack with a razor, opening new access to the contents.</p>
<p>The team responded by creating the Dorsal travel pack. It is a stylish, modern backpack with all of the zippers facing inward toward the wearer’s back. It is made of slash resistant fabric in nondescript colors to avoid the attention that more popular colorful brands draw. The team went through a series of validation tests to confirm the pain and confirm the solution. The tests also helped the team refine the concept to meet the needs of their targeted travelers. The team also confirmed that they can sell the pack directly from their website.</p>
<p>One of the final tests was to analyze the expected profitability of the travel pack. The team reached out to members of their social networks and invited those who had recently traveled or were planning to travel in the near future to help. They were able to get 107 responses from potential customers who had traveled or were about to travel internationally. The respondents were shown the backpack and its features. They were asked to rate the innovation and offer suggestions to improve it. They were also asked “What is the most you would be willing to pay for the Dorsal travel pack?” Finally, they provided information about their travel patterns as well as demographics.</p>
</section>
<section id="dorsal-pack-data" class="level3">
<h3 class="anchored" data-anchor-id="dorsal-pack-data">Dorsal Pack data</h3>
<p>Because the travel pack is a durable good for most travelers, we focusing on the of willingness to pay from respondents who had traveled or were planning to travel soon. We see the following willingness to pay responses:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>dp <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">wtp =</span> <span class="fu">c</span>(<span class="dv">64</span>, <span class="dv">18</span>, <span class="dv">46</span>, <span class="dv">92</span>, <span class="dv">110</span>, <span class="dv">138</span>, <span class="dv">113</span>, <span class="dv">89</span>, <span class="dv">0</span>, <span class="dv">258</span>, <span class="dv">205</span>, <span class="dv">0</span>, <span class="dv">18</span>, <span class="dv">202</span>, <span class="dv">46</span>, <span class="dv">258</span>, <span class="dv">0</span>, <span class="dv">141</span>, <span class="dv">0</span>, <span class="dv">46</span>, <span class="dv">61</span>, <span class="dv">101</span>, <span class="dv">64</span>, <span class="dv">215</span>, <span class="dv">95</span>, <span class="dv">43</span>, <span class="dv">46</span>, <span class="dv">46</span>, <span class="dv">132</span>, <span class="dv">21</span>, <span class="dv">18</span>, <span class="dv">113</span>, <span class="dv">9</span>, <span class="dv">18</span>, <span class="dv">21</span>, <span class="dv">18</span>, <span class="dv">104</span>, <span class="dv">6</span>, <span class="dv">0</span>, <span class="dv">101</span>, <span class="dv">6</span>, <span class="dv">224</span>, <span class="dv">322</span>, <span class="dv">18</span>, <span class="dv">316</span>, <span class="dv">156</span>, <span class="dv">104</span>, <span class="dv">322</span>, <span class="dv">285</span>, <span class="dv">208</span>, <span class="dv">316</span>, <span class="dv">0</span>, <span class="dv">288</span>, <span class="dv">95</span>, <span class="dv">6</span>, <span class="dv">52</span>, <span class="dv">46</span>, <span class="dv">0</span>, <span class="dv">18</span>, <span class="dv">64</span>, <span class="dv">98</span>, <span class="dv">248</span>, <span class="dv">18</span>, <span class="dv">110</span>, <span class="dv">0</span>, <span class="dv">67</span>, <span class="dv">0</span>, <span class="dv">18</span>, <span class="dv">0</span>, <span class="dv">89</span>, <span class="dv">132</span>, <span class="dv">101</span>, <span class="dv">18</span>, <span class="dv">215</span>, <span class="dv">18</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">104</span>, <span class="dv">285</span>, <span class="dv">3</span>, <span class="dv">46</span>, <span class="dv">141</span>, <span class="dv">322</span>, <span class="dv">291</span>, <span class="dv">89</span>, <span class="dv">0</span>, <span class="dv">101</span>, <span class="dv">113</span>, <span class="dv">67</span>, <span class="dv">58</span>, <span class="dv">132</span>, <span class="dv">215</span>, <span class="dv">224</span>, <span class="dv">291</span>, <span class="dv">9</span>, <span class="dv">291</span>, <span class="dv">267</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">61</span>, <span class="dv">178</span>, <span class="dv">285</span>, <span class="dv">64</span>, <span class="dv">126</span>, <span class="dv">0</span>, <span class="dv">101</span>, <span class="dv">15</span>))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect the data</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 107
Columns: 1
$ wtp &lt;dbl&gt; 64, 18, 46, 92, 110, 138, 113, 89, 0, 258, 205, 0, 18, 202, 46, 25…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      wtp       
 Min.   :  0.0  
 1st Qu.: 18.0  
 Median : 67.0  
 Mean   :102.3  
 3rd Qu.:141.0  
 Max.   :322.0  </code></pre>
</div>
</div>
</section>
<section id="homework-questions" class="level3">
<h3 class="anchored" data-anchor-id="homework-questions">Homework Questions:</h3>
<ol type="1">
<li><p><strong>Calculate quantity from willingness to pay:</strong></p>
<ol type="a">
<li><p>Working under the assumption of a durable good, the Dorsal pack team collected data on the willingness to pay of their targeted customers. In the absence of quantity data, use the willingness to pay (wtp) data in the dp tibble to calculate the quantities for the Dorsal pack demand curve.</p></li>
<li><p>How many unique values of willingness to pay are there?</p></li>
<li><p>What is the average of the <strong>unique</strong> values of willingness to pay?</p></li>
<li><p>What is the average of all of the values of willingness to pay?</p></li>
</ol></li>
<li><p><strong>Visualize dorsal pack wtp data:</strong>. Visualize the relationship between the price (wtp) and quantity in a scatterplot of the Dorsal pack demand data. Does the relationship between willingness to pay and quantity seem to be more linear or more nonlinear?</p></li>
<li><p><strong>Dorsal pack - linear demand:</strong></p>
<ol type="a">
<li>Assume that the relationship between willingness to pay is linear. Estimate the linear model.</li>
<li>Calculate the AIC value for the linear demand model.</li>
</ol></li>
<li><p><strong>Dorsal pack - exponential demand:</strong></p>
<ol type="a">
<li>Assume that the relationship between willingness to pay is nonlinear - specifically an exponential demand curve. Estimate the exponential demand model.</li>
<li>Calculate the AIC value for the exponential demand model.</li>
</ol></li>
<li><p><strong>Best model:</strong> Is the linear demand model a better fit for the Dorsal Pack data or the exponential demand model?</p></li>
<li><p><strong>Model interpretation:</strong></p>
<ol type="a">
<li><p>What is the F-statistic of the best model?</p></li>
<li><p>What is the R-squared of the best model?</p></li>
<li><p>In the best model, how confident are you that the estimated slope (<code>wtp</code>) coefficient is different from zero?</p></li>
</ol></li>
<li><p><strong>Calculate demand:</strong></p>
<ol type="a">
<li><p>What is the level of demand when price is P = 100?</p></li>
<li><p>What is the level of demand when price is P = 200?</p></li>
</ol></li>
</ol>
<hr>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="sec-elasticity" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="sec-elasticity"><span class="header-section-number">4.7</span> Appendix: Elasticity of Demand</h2>
<p>It is traditional, when learning about demand curves, to turn our attention to the sensitivity of customers as measured by the elasticity of demand. Since customers provide the flow of funds that ultimately finance all of the activities in the firm, they are critical to performance. If customers are unwilling to pay, there is no hope for a competitive advantage to generate superior performance. The rate at which quantity demanded falls as price rises is the slope of the demand curve and defines how sensitive consumers are to changes in prices. Customers who are sensitive to prices will demand price cuts and resist our attempts to raise prices by buying the solutions of others. Price sensitivity can guide you in choosing solutions where customers are less sensitive to prices in addition to assisting in pricing decisions.</p>
<p>Measures of price sensitivity are complicated by their reliance on the unit of measurement. For example, if I say that the price of gasoline fell by 1, you immediately wonder if I mean $1 or 1 cent. Pennies versus dollars is an important difference of units of money. If I say that price fell by $1.00, you may be tempted to run out and fill your tank. However, your next question should be, “Price fell by $1.00 per what?” If it is $1.00 off from 1000 gallons, it is not so attractive. Units matter. To resolve the problem of units, economists express sensitivity to price in terms of percentage changes. This sensitivity measure is independent of units and is called <strong>elasticity</strong>. The sensitivity of the changes is expressed as a percentage change in the one thing leading to some percentage change in the other thing.</p>
<p>The traditional measure of price sensitivity is the <strong>own-price elasticity of demand</strong> which reveals the percentage change in quantity demanded that results from a one percent change in price.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> The method to calculate the own-price elasticity of demand using calculus is</p>
<p><span class="math display">\[
   \mathsf{\epsilon_{Q_x,P_x} =  \frac{d Q_{x}}{d P_{x}} \cdot \frac{P_{x}}{Q_{x}} }
\]</span></p>
<p>where <span class="math inline">\(\epsilon\)</span>, the Greek letter “epsilon” is used to denote elasticity, <span class="math inline">\(\mathsf{Q_x}\)</span> is quantity demanded of product <span class="math inline">\(\mathsf{x}\)</span>, <span class="math inline">\(\mathsf{P_x}\)</span> is the price of <span class="math inline">\(\mathsf{x}\)</span>, and <span class="math inline">\(\mathsf{\frac{dQ_{x}}{dP_{x}}}\)</span> is the derivative (slope) of the demand curve.</p>
<p>To characterize a customer’s sensitivity to price we compare the absolute value of elasticity to one. When <span class="math inline">\(|\epsilon| &gt;1\)</span>, demand is <em>elastic</em>; when <span class="math inline">\(| \epsilon| &lt;1\)</span>, demand is <em>inelastic</em>; when <span class="math inline">\(| \epsilon| =1\)</span>, demand is <em>unitary elastic</em>. These labels reflect the size of the response in quantity demanded to a change in price. When you know the elasticity of demand, you know how consumption and revenue will change in response to a change in price. When the own-price elasticity of demand, in absolute value, is greater than one, revenue will rise when you lower the price. The fact that demand is elastic means that a one percent reduction in price will lead to more than a one percent increase in consumption. Since quantity goes up more than price goes down, revenue will rise. By the same logic and math, when the elasticity of demand is inelastic, revenue rises when price is increased because a one percent increase in price will result in less than a one percent reduction in quantity demanded.</p>
<p>Calculating percentage changes is straightforward by simply finding the difference between the new value and the original value and dividing by the original value. For example, if a price went from $50 to $55, the percentage change is <span class="math display">\[
  \mathsf{ \dfrac{P_{1}-P_{0}}{P_{0}} = \dfrac{55-50}{50} = 0.1}
\]</span> or in words, a 10% increase in price. We find the elasticity of one variable with respect to another by dividing the percentage change in the first variable by the percentage change in the second.</p>
<p>The <em>own-price elasticity of demand</em> shows us how sensitive customers of <span class="math inline">\(\mathsf{X}\)</span> are to changes in the price of <span class="math inline">\(\mathsf{X}\)</span>. We call it the “own-price elasticity of demand” to distinguish it from the influence of prices of other goods. We call their influence the “cross-price elasticity of demand.” If the price of <span class="math inline">\(\mathsf{X}\)</span> is increased by one percent, by what percent do customers decrease their quantity demanded of <span class="math inline">\(\mathsf{X}\)</span>? This is the own-price elasticity of demand and it is expressed mathematically as <span class="math display">\[\begin{align}
   \mathsf{\epsilon_{Q_x,P_x}} &amp; = \mathsf{\dfrac{\%\Delta Q_x }{\%\Delta P_x }
    = \dfrac{\dfrac{Q_1-Q_0}{Q_0}}{\dfrac{P_1-P_0}{P_0}}
    = \dfrac{\dfrac{\Delta Q_{x}}{Q_0}}{\dfrac{\Delta P_{x}}{P_0}}
    = \dfrac{\Delta Q_{x}}{Q_{0}}\dfrac{P_{0}}{\Delta P_{x}}} \notag \\
   &amp;= \mathsf{\dfrac{\Delta Q_{x}}{\Delta P_{x}} \cdot \dfrac{P_{0}}{Q_{0}}}
\end{align}\]</span></p>
<p>where <span class="math inline">\(\mathsf{\Delta}\)</span> signifies a change. Notice that the first part of the elasticity formula is the slope of the demand curve. Remember that slope is the rise of a function divided by its run. The change in quantity is the “rise” of the demand curve and the change in price is the “run.” Therefore, <span class="math inline">\(\mathsf{\frac{\Delta Q_{x}}{\Delta P_{x}}}\)</span> is the rise over the run (slope) of the demand curve. In short, the own-price elasticity of demand is the slope of the demand curve multiplied by price over quantity.</p>
<p>If we let the changes in price become infinitely small they become the derivative of quantity with respect to price and the elasticity equation becomes the more useful calculus version of elasticity:</p>
<p><span class="math display">\[
   \mathsf{\epsilon_{Q_x,P_x} =  \dfrac{d Q_{x}}{d P_{x}} \cdot \dfrac{P_{x}}{Q_{x}}}
\]</span> where <span class="math inline">\(\mathsf{\frac{dQ_{x}}{dP_{x}}}\)</span> is the derivative (slope) of the demand curve.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> The elasticity is a number that we interpret, in words, as a one percent change in price of <span class="math inline">\(\mathsf{x}\)</span> causing a <span class="math inline">\(\mathsf{\epsilon_{Q_x,P_x}}\)</span> percent change in quantity demanded. More specifically, if the own-price elasticity is <span class="math inline">\(\mathsf{\epsilon_{Q_x,P_x} = -0.5}\)</span>, we say that a one percent increase in price leads to a 0.5 percent <em>decrease</em> in quantity demanded.</p>
<p>Consider a rubber band. If a force is applied and the rubber band stretches a long way, it is more elastic than a rubber band that stretches less. Similarly, when the force of a one percent increase in price is applied to a customer, that customer’s demand is elastic when the customer reduces consumption by more than one percent. When a one percent price hike is presented to an inelastic customer, the customer reduces quantity demand by less than one percent. When the customer is unitary elastic, a one percent increase in price results in a one percent reduction in quantity demanded.</p>
<p>A customer’s sensitivity to price is influenced by several factors. In general, anything that shifts the intercept or the slope of the demand curve will also change the elasticity at a particular price. For example, if concerns about the health effects of saturated fat reduce the demand for cheese, customers’ demand will also be more elastic at the historical price. Logically, this is because the health concerns will exacerbate the reductions in consumption when price is raised. Mathematically, customers become more elastic (elasticity becomes a larger negative number) because the quantity in the denominator falls while the slope and price stay the same. Time will also change elasticity. In the short-run, we have fewer substitutes and are therefore more inelastic. Similarly, we are more inelastic about consuming categories of goods than consuming specific goods. For example, demand for New Balance running shoes is much more elastic than for clothing in general.</p>
<section id="elasticity-with-linear-demand-curves" class="level3">
<h3 class="anchored" data-anchor-id="elasticity-with-linear-demand-curves">Elasticity with Linear Demand Curves</h3>
<p>Now let’s look at the relationship between elasticity and the demand curve. From the elasticity equation, we can see that the own-price elasticity of any demand curve is the slope of the demand curve multiplied by <span class="math inline">\(\mathsf{\frac{P}{Q}}\)</span>. This means that the elasticity is proportional to the slope of the demand curve but not the same thing as the slope. As the ratio of price and quantity changes while moving along the demand curve, the elasticity also changes. If the slope of the demand curve is -2 at every point on the curve but the elasticity differs along the curve because the ratio of price and quantity is changing.</p>
<p>For example, at a price of $250, the elasticity is very different from the elasticity at a price of $750.</p>
<p><span class="math display">\[\begin{align}
  \mathsf{\epsilon_{Q_x= 1500,P_x = 250}} &amp;= \mathsf{-2 \frac{250}{1500}} &amp;  \mathsf{\epsilon_{Q_{x} =500,P_{x}=750}} &amp;= \mathsf{-2 \cdot \dfrac{750}{500}} \\
                                          &amp;= -0.3333                      &amp;                                           &amp;= -3.0
\end{align}\]</span> When the demand curve becomes steeper, the slope (derivative) becomes a larger negative number and demand becomes more elastic.</p>
<p>Elasticity does not only pertain to the sensitivity of customers of a good. The sensitivity of any relationship where one thing causes another can be characterized by an elasticity. As we have seen, demand curves depend on many things besides the price of the good. For example, the demand curve <span class="math inline">\(\mathsf{Q_{x}(P_{x}) = a - bP_{x} + cP_{y} + dM}\)</span> implies that the price of <span class="math inline">\(\mathsf{Y}\)</span> and income (<span class="math inline">\(\mathsf{M}\)</span>) also determine demand for <span class="math inline">\(\mathsf{X}\)</span>. The <strong>cross-price elasticity</strong> of demand between <span class="math inline">\(\mathsf{X}\)</span> and <span class="math inline">\(\mathsf{Y}\)</span> displays the sensitivity of demand for <span class="math inline">\(\mathsf{X}\)</span> to changes in the price of <span class="math inline">\(\mathsf{Y}\)</span>. The cross-price elasticity is calculated in the same way as the own price elasticity with the appropriate substitution of <span class="math inline">\(\mathsf{P_{y}}\)</span> for <span class="math inline">\(\mathsf{P_{x}}\)</span>:</p>
<p><span class="math display">\[
  \mathsf{\epsilon_{Q_{x},P_{y}} = \dfrac{dQ_{x}}{dP_{y}} \cdot \dfrac{P_{y}}{Q_{x}}.}
\]</span></p>
<p>While the calculation of the cross-price elasticity of demand is the same as the own-price elasticity of demand, the interpretation of the elasticity is not. With the cross-price elasticity, we are looking at the sign to interpret its impact on demand. If the cross-price elasticity is positive, the good <span class="math inline">\(\mathsf{Y}\)</span> is a substitute for good <span class="math inline">\(\mathsf{X}\)</span>. If the cross-price elasticity is positive it means that a one percent increase in the price of <span class="math inline">\(\mathsf{Y}\)</span> results in an increase in consumption of <span class="math inline">\(\mathsf{X}\)</span>. We know from the law of demand that an increase in <span class="math inline">\(\mathsf{P_{y}}\)</span> results in a decrease in quantity demanded for <span class="math inline">\(\mathsf{Q_{y}}\)</span>. If demand for <span class="math inline">\(\mathsf{X}\)</span> also increases, it must be because consumers that were consuming <span class="math inline">\(\mathsf{Y}\)</span> have begun consuming <span class="math inline">\(\mathsf{X}\)</span>. That makes <span class="math inline">\(\mathsf{X}\)</span> a substitute for <span class="math inline">\(\mathsf{Y}\)</span>. For example, sports drinks would be expected to be substitutes for cola and the cross-price elasticity should be positive.</p>
<p>If the cross-price elasticity is negative, the good <span class="math inline">\(\mathsf{Y}\)</span> is a complement of <span class="math inline">\(\mathsf{X}\)</span>. If <span class="math inline">\(\mathsf{P_{y}}\)</span> increases, then <span class="math inline">\(\mathsf{Q_{y}}\)</span> decreases. If <span class="math inline">\(\mathsf{Q_{x}}\)</span> is also caused to decrease by the increase in <span class="math inline">\(\mathsf{P_{y}}\)</span>, it must mean that customers stop consuming <span class="math inline">\(\mathsf{X}\)</span> when they stop consuming <span class="math inline">\(\mathsf{Y}\)</span>. This usually means that the products are consumed together and they are complementary products. For example, products consumed together like cars and gasoline are complements. If demand for cars in China increases, demand for gasoline does too. If the world supply of gasoline remains constant, the increased demand drives up price. We may be quite inelastic with respect to gasoline prices but our cross-price elasticity for gas-guzzling cars is quite large. High gas prices cut gas consumption by a little and gas-guzzling car consumption by a lot.</p>
</section>
<section id="elasticity-with-nonlinear-exponential-demand-curves" class="level3">
<h3 class="anchored" data-anchor-id="elasticity-with-nonlinear-exponential-demand-curves">Elasticity with Nonlinear (Exponential) Demand Curves</h3>
<p>The basic formula for the own-price elasticity of demand, <span class="math inline">\(\mathsf{\epsilon_{Q_{x},P_{y}} = \frac{dQ_{x}}{dP_{y}} \cdot \frac{P_{y}}{Q_{x}}}\)</span> is the same for linear and nonlinear demand curves alike. However, the slope (derivative) of nonlinear demand curves differs from linear demand curves so the specific formula for elasticity in nonlinear demand curves deserves attention.</p>
<p>The exponential demand curve has the form <span class="math inline">\(\mathsf{Q = ae^{-bP}}\)</span>. The own-price elasticity of demand for this form is <span class="math display">\[\begin{align}
\mathsf{\epsilon_{Q,P}} &amp;= \mathsf{\dfrac{dQ}{dP} \cdot \dfrac{P}{Q} = -bae^{-bP} \cdot \dfrac{P}{Q}} \notag \\[9pt]
                         &amp;= \mathsf{\dfrac{-bae^{-bP}P}{ae^{-bp}}} \notag \\[9pt]
                         &amp;= \mathsf{-bP}
\end{align}\]</span></p>
<p>This means that the own-price elasticity of the exponential demand curve is negative one when <span class="math inline">\(\mathsf{P= -\frac{1}{b}}\)</span>.</p>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>The own-price elasticity of demand is focused on the change of quantity demanded attributable to a change in the price of the product. In practice, we can find the elasticity of anything that causes another thing. For example, the cross-price elasticity of demand shows how demand changes as the price of another good changes and income elasticity of demand shows how demand changes as income changes.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>A brief review of derivatives may be useful. For a general function like <span class="math inline">\(\mathsf{y = bx^{n}}\)</span>, the slope of the function is found through the derivative which is <span class="math inline">\(\mathsf{dy/dx = nbx^{n-1}}\)</span>. In words, a derivative is taken by bringing down the exponent, multiplying it by the slope parameter, and reducing the exponent by one. Consider the following example. The demand curve can be written as <span class="math inline">\(\mathsf{Q = a - bP}\)</span> and can be equivalently written as <span class="math inline">\(\mathsf{Q = ax^{0} - bx^{1}}\)</span>. The elasticity is the derivative times price divided by quantity. Taking the derivative of the demand curve we get <span class="math inline">\(\mathsf{dQ/dP = 0\times a\times x^{-1} -1\times b\times x^{0} = -b}\)</span>. This means that the complete elasticity is $ $. For a more specific example, consider the demand curve <span class="math inline">\(\mathsf{Q_{x} = 1000 - 10P_{x}}\)</span>. We can rewrite this as <span class="math inline">\(\mathsf{Q_{x} = 1000P_{x}^{0} - 10P_{x}^{1}}\)</span>. The slope of the demand curve is the derivative. It is found by bringing down the exponent of each term to multiply it by the rest of the term and then subtracting one from the exponent as follows: <span class="math inline">\(\mathsf{dQ/dP = 0 \times 100 \times P_{x}^{-1} - 1 \times 10 \times P_{x}^{0} = -10}\)</span>. The elasticity is <span class="math inline">\(\mathsf{\epsilon = (dQ/dP) \times (P/Q) = -10\times P/Q}\)</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./uncertainty_profit.html" class="pagination-link" aria-label="Profit Uncertainty">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Profit Uncertainty</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./durable_demand.html" class="pagination-link" aria-label="Estimating Demand of Durable Goods Using R">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimating Demand of Durable Goods Using R</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>